### ISSUE TITLE
Invalid name: "Firefox Emoji Font"

### ISSUE THREAD

**Issue by Rudloff** [mozilla/fxemoji#7]
I get an error when I run `npm install`:

```
npm ERR! install Couldn't read dependencies
npm ERR! Error: Invalid name: "Firefox Emoji Font"
npm ERR!     at ensureValidName (/usr/lib/nodejs/normalize-package-data/lib/fixer.js:284:15)
npm ERR!     at Object.module.exports.fixNameField (/usr/lib/nodejs/normalize-package-data/lib/fixer.js:199:5)
npm ERR!     at /usr/lib/nodejs/normalize-package-data/lib/normalize.js:29:38
npm ERR!     at Array.forEach (native)
npm ERR!     at normalize (/usr/lib/nodejs/normalize-package-data/lib/normalize.js:28:15)
npm ERR!     at final (/usr/lib/nodejs/read-package-json/read-json.js:342:33)
npm ERR!     at then (/usr/lib/nodejs/read-package-json/read-json.js:126:33)
npm ERR!     at /usr/lib/nodejs/read-package-json/read-json.js:331:40
npm ERR!     at evalmachine.<anonymous>:272:14
npm ERR!     at /usr/lib/nodejs/graceful-fs/graceful-fs.js:102:5
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.16.0-4-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/pierre/www/fxemoji
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pierre/www/fxemoji/npm-debug.log
npm ERR! not ok code 0
```

**Comment by pivanov** [comment]
It's fixed now :) thanks for your help
